<?php

namespace aplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * daneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class daneRepository extends EntityRepository
{
}
