<?php

namespace aplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * uzytkownicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uzytkownicyRepository extends EntityRepository
{
}
